-- MAAP Project with Professor Seo.
-- 2023-01-03
-- Writer & Authority : JungSu Han
------------------------------------
-- DROP TABLE
------------------------------------
-- (1) part: USERS
DROP TABLE MP_USER;
DROP TABLE MP_USER_INFO;
DROP TABLE MP_USER_CERTIFICATION;
-- (2) part: LAND & ROOM
DROP TABLE LAND;
DROP TABLE ROOM;

------------------------------------
-- CREATE TABLE
------------------------------------
-- (1) part: USER
CREATE TABLE MP_USER
(
  USER_ID VARCHAR(30) NOT NULL,
  USER_PASSWORD VARCHAR(30) NOT NULL,
  PHONE_NUMBER VARCHAR(30) NOT NULL,
  EMAIL_ADDRESS VARCHAR(30) NOT NULL,
  COMPANY VARCHAR(30) NOT NULL,
  MANAGER BOOLEAN NOT NULL,
  PRIMARY KEY (USER_ID)
);
CREATE TABLE MP_USER_INFO
(
  USER_ID VARCHAR(30) NOT NULL,
  PROFILE_IMG MEDIUMBLOB NOT NULL,
  REGISTRATION_DTM TIMESTAMP DEFAULT NOW() NOT NULL,
  DEPARTMENT VARCHAR(30),
  POSITION VARCHAR(30),
  WRITTEN_ARTICLE_NUM INT DEFAULT 0 NOT NULL,
  GRADE VARCHAR(30),
  NATION_CODE VARCHAR(30),
  DEL_FLAG BOOLEAN DEFAULT FALSE NOT NULL,
  TESTING_PROJECT_NUM INT DEFAULT 0 NOT NULL,
  STATUS INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (USER_ID)
);
CREATE TABLE MP_USER_CERTIFICATION
(
  USER_ID VARCHAR(30) NOT NULL,
  PHONE VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  PHONE_CERT_NUM VARCHAR(30),
  EMAIL_CERT_NUM VARCHAR(30),
  PRIMARY KEY (USER_ID)
);
------------------------------------
-- (2) part: LAND & ROOM
CREATE TABLE LNAD
(
  LAND_ID VARCHAR(30) NOT NULL,
  LAND_OWNER VARCHAR(30) NOT NULL,
  LAND_NUM INT DEFAULT 0 NOT NULL,`MP_USER_CERTIFICATION`
  LAND_INFO VARCHAR(128) NOT NULL,
  LAND_TOTAL_SIZE INT DEFAULT 0 NOT NULL,
  SOLD_LAND INT DEFAULT 0 NOT NULL,
  SELL_LAND INT DEFAULT 0 NOT NULL,
  FULLY_SOLD BOOLEAN NOT NULL,
  MANAGER VARCHAR(30) NOT NULL,`ROOM`
  PRIMARY KEY (LAND_ID)
);
CREATE TABLE ROOM
(
  ROOM_ID VARCHAR(30) NOT NULL,
  LAND_ASSO VARCHAR(30) NOT NULL,
  ROOM_NAME VARCHAR(30) NOT NULL,
  ROOM_SIZE VARCHAR(30) NOT NULL,
  ROOM_LOCATE VARCHAR(50) NOT NULL,
  ROOM_INFO VARCHAR(128) NOT NULL,
  ROOM_OWNER BOOLEAN NOT NULL,
  PRIMARY KEY (ROOM_ID)
);