query = {
    # LAND
    "USER_ADD": "INSERT INTO TB_USER (USER_ID, USER_PASSWORD, PHONE_NUMBER, EMAIL_ADDRESS, COMPANY, MANAGER) VALUES (%s, %s, %s, %s, %s, %s)",
    "USER_FIND_ID": "SELECT USER_ID FROM TB_USER WHERE PHONE_NUMBER = %s AND EMAIL_ADDRESS = %s",
    "USER_FIND_PASSWORD": "SELECT USER_ID FROM TB_USER WHERE USER_ID = %s AND PHONE_NUMBER = %s AND EMAIL_ADDRESS = %s",
    "USER_CHECK_ID": "SELECT USER_ID, MANAGER FROM TB_USER WHERE USER_ID = %s",
    "USER_CHECK_INFO": "SELECT USER_ID FROM TB_USER WHERE PHONE_NUMBER = %s OR EMAIL_ADDRESS = %s",
    "USER_GET_ALL": "SELECT * FROM TB_USER ",
    "USER_GET_ONE": "SELECT USER_ID, PHONE_NUMBER, EMAIL_ADDRESS, COMPANY, MANAGER FROM TB_USER WHERE USER_ID = %s AND USER_PASSWORD = %s",
    "USER_UPDATE": "UPDATE TB_USER SET USER_PASSWORD = %s, PHONE_NUMBER = %s, EMAIL_ADDRESS = %s, COMPANY = %s WHERE USER_ID = %s",
    "USER_UPDATE_PASSWORD": "UPDATE TB_USER SET USER_PASSWORD = %s WHERE USER_ID = %s",
    "USER_UPDATE_MANAGER": "UPDATE TB_USER SET MANAGER = %s WHERE USER_ID = %s",
    "USER_INFO_ADD": "INSERT INTO TB_USER_INFO (USER_ID, PROFILE_IMG) VALUES (%s, %s)",
    "USER_INFO_GET_ONE": "SELECT * FROM TB_USER_INFO WHERE USER_ID = %s",
    "USER_INFO_UPDATE": "UPDATE TB_USER_INFO SET PROFILE_IMG = %s WHERE USER_ID = %s",

    # ROOM
    "ROOM_ADD": "INSERT INTO ROOM (ROOM_ID, LAND_ASSO, ROOM_NAME, ROOM_SIZE, ROOM_LOCATE, ROOM_INFO, ROOM_OWNER) VALUES (%s, %s, %s, %s, %s, %s, %s)",
}